API_KEY = "YOUR API KEY"
SECRET_KEY = "YOUR SECRET KEY"
SYMBOL = "AAPL"
TICKERS = "Q.AAPL"
HEADERS = {
    'APCA-API-KEY-ID': API_KEY,
    'APCA-API-SECRET-KEY': SECRET_KEY
}
BARS_URL = 'https://data.alpaca.markets/v1/bars'
